cam_data=
{
"cam_address": "127.0.0.1:36680",
"visca_server_address": "127.0.0.1:8080",

"cam_selectors": [
    {"name" : "Cam1",
     "serialnumber" : "5203656101150",
     "type" : "visca_joystick",
     "address" : "192.168.0.20",
     "slew_pan_velocity" : 10,
     "slew_pan_max" : 16,
     "slew_tilt_velocity" : 15,
     "slew_tilt_max" : 20,
     "max_preset" : 10},
    {"name" : "Cam2",
     "serialnumber" : "5309115900007",
     "type" : "visca_jog",
     "address" : "1",
     "slew_pan_velocity" : 10,
     "slew_tilt_velocity" : 15,
     "max_preset" : 10}
    // Sample entry to show parameters for aver_ptzapp camera
    //{"name" : "Cam2",
    // "serialnumber" : "5309115900007",
    // "type" : "aver_ptzapp",
    // "address" : 1,
    // "max_preset" : 10}
  ],

"cam_presets": [
   {"name" : "Ambo",
    "camera" : "Cam1",
    "preset" : "1"},
   {"name" : "Altar",
    "camera" : "Cam1",
    "preset" : "2"},
   {"name" : "Musicians",
    "camera" : "Cam1",
    "preset" : "3"},
   {"name" : "Sanctuary Wide",
    "camera" : "Cam1",
    "preset" : "4"},
   {"name" : "Musicians Right",
    "camera" : "Cam1",
    "preset" : "6"},
   {"name" : "Cam1 Center",
    "camera" : "Cam1",
    "preset" : "0"},
   {"name" : "Cam1 Ambo",
    "camera" : "Cam1",
    "preset" : "1"},
   {"name" : "Cam1 Altar",
    "camera" : "Cam1",
    "preset" : "2"},
   {"name" : "Cam1 Musicians",
    "camera" : "Cam1",
    "preset" : "3"},
   {"name" : "Cam1 Sanctuary Wide",
    "camera" : "Cam1",
    "preset" : "4"},
   {"name" : "Cam1 Sanctuary Mid",
    "camera" : "Cam1",
    "preset" : "5"},
   {"name" : "Cam1 Musicians Right",
    "camera" : "Cam1",
    "preset" : "6"},
   {"name" : "Cam1 Ambo Mid",
    "camera" : "Cam1",
    "preset" : "7"},
   {"name" : "Cam1 Sanctuary North",
    "camera" : "Cam1",
    "preset" : "8"},
   {"name" : "Cam1 Sanctuary South",
    "camera" : "Cam1",
    "preset" : "9"},

   {"name" : "Center",
    "camera" : "Cam2",
    "preset" : "0"},
   {"name" : "Sanctuary Mid",
    "camera" : "Cam2",
    "preset" : "5"},
   {"name" : "Ambo Mid",
    "camera" : "Cam2",
    "preset" : "7"},
   {"name" : "Sanctuary North",
    "camera" : "Cam2",
    "preset" : "8"},
   {"name" : "Sanctuary South",
    "camera" : "Cam2",
    "preset" : "9"},
   {"name" : "Cam2 Center",
    "camera" : "Cam2",
    "preset" : "0"},
   {"name" : "Cam2 Ambo",
    "camera" : "Cam2",
    "preset" : "1"},
   {"name" : "Cam2 Altar",
    "camera" : "Cam2",
    "preset" : "2"},
   {"name" : "Cam2 Musicians",
    "camera" : "Cam2",
    "preset" : "3"},
   {"name" : "Cam2 Sanctuary Wide",
    "camera" : "Cam2",
    "preset" : "4"},
   {"name" : "Cam2 Sanctuary Mid",
    "camera" : "Cam2",
    "preset" : "5"},
   {"name" : "Cam2 Musicians Right",
    "camera" : "Cam2",
    "preset" : "6"},
   {"name" : "Cam2 Ambo Mid",
    "camera" : "Cam2",
    "preset" : "7"},
   {"name" : "Cam2 Sanctuary North",
    "camera" : "Cam2",
    "preset" : "8"},
   {"name" : "Cam2 Sanctuary South",
    "camera" : "Cam2",
    "preset" : "9"}
  ]
};