cam_data=
{
"cam_address": "127.0.0.1:36680",

"cam_selectors": [
    {"name" : "Cam1",
    "serialnumber" : "5308883500050"},
    {"name" : "Cam2",
    "serialnumber" : "5309115900007"}
  ],

"cam_presets": [
   {"name" : "Center",
    "camera" : "Cam1",
    "preset" : "0"},
   {"name" : "Ambo",
    "camera" : "Cam1",
    "preset" : "1"},
   {"name" : "Altar",
    "camera" : "Cam1",
    "preset" : "2"},
   {"name" : "Musicians",
    "camera" : "Cam1",
    "preset" : "3"},
   {"name" : "Sanctuary Wide",
    "camera" : "Cam1",
    "preset" : "4"},
   {"name" : "Sanctuary Mid",
    "camera" : "Cam1",
    "preset" : "5"},
   {"name" : "Musicians Right",
    "camera" : "Cam1",
    "preset" : "6"},
   {"name" : "Ambo Mid",
    "camera" : "Cam1",
    "preset" : "7"},
   {"name" : "Sanctuary North",
    "camera" : "Cam1",
    "preset" : "8"},
   {"name" : "Sanctuary South",
    "camera" : "Cam1",
    "preset" : "9"},
   {"name" : "Cam2 Center",
    "camera" : "Cam2",
    "preset" : "0"},
   {"name" : "Cam2 Ambo",
    "camera" : "Cam2",
    "preset" : "1"},
   {"name" : "Cam2 Altar",
    "camera" : "Cam2",
    "preset" : "2"},
   {"name" : "Cam2 Musicians",
    "camera" : "Cam2",
    "preset" : "3"},
   {"name" : "Cam2 Sanctuary Wide",
    "camera" : "Cam2",
    "preset" : "4"},
   {"name" : "Cam2 Sanctuary Mid",
    "camera" : "Cam2",
    "preset" : "5"},
   {"name" : "Cam2 Musicians Right",
    "camera" : "Cam2",
    "preset" : "6"},
   {"name" : "Cam2 Ambo Mid",
    "camera" : "Cam2",
    "preset" : "7"},
   {"name" : "Cam2 Sanctuary North",
    "camera" : "Cam2",
    "preset" : "8"},
   {"name" : "Cam2 Sanctuary South",
    "camera" : "Cam2",
    "preset" : "9"}
  ]
};